### ISSUE TITLE
Trident Protect SnapshotRestore and BackupRestore CRs reporting error but completing

### ISSUE THREAD

**Issue by cburchett** [NetApp/tridentctl-protect#4]
Here is my SnapshotRestore CR:

```
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: mysqlapp-snaprestore1
  namespace: mysqlapp
spec:
  appArchivePath: mysqlapp_6a7fd6ca-24b0-4e84-bcb8-4e39049f1819/snapshots/20241121203035_mysqlapp-snap-1_a05499ab-6b44-4826-80d8-de5ffb55448b
  appVaultRef: c1-svm0-s3-av
  namespaceMapping:
  - source: mysqlapp
    destination: mysqlapp1
```
    
 The restore seems to work but I am getting this error message:
 
```
 kubectl -n mysqlapp get snapshotrestore -w
NAME                    STATE     ERROR   AGE
mysqlapp-snaprestore1   Running           15s
mysqlapp-snaprestore1   Running           17s
mysqlapp-snaprestore1   Running           17s
mysqlapp-snaprestore1   Error     Existing app definition is different that expected, cannot reuse the application 'mysqlapp'   17s
```

When I got to destination namespace, everything looks good:

```
kubectl -n mysqlapp1 get all,pvc
NAME             READY   STATUS    RESTARTS   AGE
pod/mysqlapp-0   1/1     Running   0          10m

NAME                        TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/mysqlapp            ClusterIP   10.103.47.48   <none>        3306/TCP   10m
service/mysqlapp-headless   ClusterIP   None           <none>        3306/TCP   10m

NAME                        READY   AGE
statefulset.apps/mysqlapp   1/1     10m

NAME                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/data-mysqlapp-0   Bound    pvc-ddbf34f0-0b7d-48c8-9762-f244070ecef5   8Gi        RWO            c1-svm0-nfs-custom-sc   <unset>                 10m
```

Here is my BackupRestore CR:

```
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: mysqlapp-backuprestore1
  namespace: mysqlapp
spec:
  appArchivePath: [Redacted path]
  appVaultRef: c1-svm0-s3-av
  namespaceMapping:
  - source: mysqlapp
    destination: mysqlapp2
```

Here is the resulting output:

```
kubectl -n mysqlapp get backuprestore -w
NAME                      STATE     ERROR   AGE
mysqlapp-backuprestore1   Running           29s
mysqlapp-backuprestore1   Running           32s
mysqlapp-backuprestore1   Running           32s
mysqlapp-backuprestore1   Running           41s
mysqlapp-backuprestore1   Running           42s
mysqlapp-backuprestore1   Running           42s
mysqlapp-backuprestore1   Running           42s
mysqlapp-backuprestore1   Running           42s
mysqlapp-backuprestore1   Running           47s
mysqlapp-backuprestore1   Error     Existing app definition is different that expected, cannot reuse the application 'mysqlapp'   47s
```

But again, everything is fine:

```
kubectl -n mysqlapp2 get all,pvc
NAME             READY   STATUS    RESTARTS   AGE
pod/mysqlapp-0   1/1     Running   0          47s
 
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/mysqlapp            ClusterIP   10.106.141.12   <none>        3306/TCP   47s
service/mysqlapp-headless   ClusterIP   None            <none>        3306/TCP   47s
 
NAME                        READY   AGE
statefulset.apps/mysqlapp   1/1     47s
 
NAME                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/data-mysqlapp-0   Bound    pvc-8efb0cfe-688e-49f0-9fdd-40bfb91a1609   8Gi        RWO            c1-svm0-nfs-custom-sc   <unset>                 50s
```

One last data point... inplace snapshot and inplace backup restores complete normally.... this only is an issue restoring to a new namespace.
